<h1 align="center"><font size="10">OGBN-arxiv hyperparameter optimisation</font></h1>

<h1 align="center"><font size="5">Hyperparameter Optimisation using VS Code and Colab Server</font></h1>

<div class="alert alert-info"><p>
This is the fifth of a series of notebooks for graph network EDA, training, inference, explainability and optimisation. This notebook searches the best hyperparametor based on the result from the best model obtain during training and testing. The best model to optomised is GraphSAGE+BatchNorm usin optuna algorithms on the ogbn-arxiv dataset. After the searc the best params will beused to train the network over ten seeds each, on a Colab GPU runtime driven from VS Code, or locally.
</p></div>

In [1]:
import os, sys, shutil, subprocess, threading, time
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules or os.path.exists("/content")
USE_DRIVE = True          # mirror the study DB and best-config files to Drive
REPO_URL = "https://github.com/Wb-az/pyg-graph-networks.git"
BRANCH = "main"

if IN_COLAB:
    if USE_DRIVE:
        from google.colab import drive
        drive.mount("/content/drive", force_remount=True)
        DRIVE_DIR = Path("/content/drive/MyDrive/GraphNetworks")
        DRIVE_DIR.mkdir(parents=True, exist_ok=True)
    repo = Path("/content/pyg-graph-networks")
    if not repo.exists():
        subprocess.run(["git", "clone", "--branch", BRANCH, REPO_URL, str(repo)], check=True)
    else:
        subprocess.run(["git", "-C", str(repo), "pull", "--ff-only"], check=True)
    os.chdir(repo)
    print(subprocess.run(["git", "log", "-1", "--format=code at %h  %s  (%cd)"],
                         capture_output=True, text=True).stdout.strip())
else:
    USE_DRIVE = False
    here = Path.cwd()
    root = next(p for p in [here, *here.parents] if (p / "pyproject.toml").exists())
    os.chdir(root)

ROOT = Path.cwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
print("project root:", ROOT)

Mounted at /content/drive
code at 5063d2e  Change triggered by colab kernel, the content remained unchanged  (Sat Sep 12 23:30:29 2026 +0100)
project root: /content/pyg-graph-networks

In [2]:
# Colab has torch + CUDA preinstalled; add the graph stack and optuna on top.
if IN_COLAB:
    %pip install -q torch_geometric==2.8.0.post1 ogb optuna

OPTUNA_SEARCH = ROOT / "src" / "node_classification" / "optuna_search.py"
if not OPTUNA_SEARCH.exists():
    raise RuntimeError(f"{OPTUNA_SEARCH} is missing: commit, push, then rerun from the top")
_src = OPTUNA_SEARCH.read_text()
if ('suggest_int("num_layers", 2, 3)' not in _src
        or 'suggest_float("dropout", 0.1, 0.6, step=0.05)' not in _src
        or 'suggest_categorical("weight_decay",' not in _src):
    raise RuntimeError(f"{OPTUNA_SEARCH} is older than this notebook: "
                       "commit, push, then rerun from the top")
print(OPTUNA_SEARCH, "ok")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 83.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 44.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 28.9 MB/s eta 0:00:00
/content/pyg-graph-networks/src/node_classification/optuna_search.py ok

In [3]:
OPTUNA_DIR = ROOT / "outputs" / "optuna"
METRICS_DIR = ROOT / "outputs" / "metrics" / "ogbn-arxiv"
CKPT_DIR = ROOT / "outputs" / "checkpoints" / "ogbn-arxiv"
OPTUNA_DIR.mkdir(parents=True, exist_ok=True)
METRICS_DIR.mkdir(parents=True, exist_ok=True)
CKPT_DIR.mkdir(parents=True, exist_ok=True)


def sync(src: Path, dst: Path):
    """Copy a directory tree; files in src overwrite dst (dirs_exist_ok merges)."""
    if src.exists():
        shutil.copytree(src, dst, dirs_exist_ok=True)


if USE_DRIVE:
    DRIVE_OPTUNA = DRIVE_DIR / "optuna"
    DRIVE_METRICS = DRIVE_DIR / "metrics" / "ogbn-arxiv"
    DRIVE_CKPT = DRIVE_DIR / "checkpoints" / "ogbn-arxiv"
    names = sorted(p.name for p in DRIVE_DIR.iterdir())
    dups = [n for n in names if n.startswith(("optuna (", "metrics (", "checkpoints ("))]
    if dups:
        raise RuntimeError(f"Duplicate folders in {DRIVE_DIR}: {dups}. In the Drive web UI "
                           "merge them into the folder without the suffix, delete the "
                           "copies, then rerun from the top")
    for d in (DRIVE_OPTUNA, DRIVE_METRICS, DRIVE_CKPT):
        if not d.exists():
            d.mkdir(parents=True)
    # Restore the study DB (resumable trials), earlier best-config files, and checkpoints.
    sync(DRIVE_OPTUNA, OPTUNA_DIR)
    sync(DRIVE_METRICS, METRICS_DIR)
    sync(DRIVE_CKPT, CKPT_DIR)
    print("restored from Drive:", sorted(p.name for p in OPTUNA_DIR.glob("*.db")))


def backup():
    if USE_DRIVE:
        sync(OPTUNA_DIR, DRIVE_OPTUNA)
        sync(METRICS_DIR, DRIVE_METRICS)
        sync(CKPT_DIR, DRIVE_CKPT)


def run_with_backup(fn, *args, backup_every_s=120, **kwargs):
    """Run fn(*args, **kwargs) while periodically backing up to Drive, so a
    Colab runtime cut mid-search loses at most backup_every_s of trials, not
    the whole study. The SQLite study DB persists each trial as it completes,
    so a backup mid-run always has every trial finished up to that point."""
    stop = threading.Event()

    def keep_backing_up():
        while not stop.wait(backup_every_s):
            try:
                backup()
            except OSError as err:          # Drive hiccup: try again next round
                print("backup failed:", err)

    threading.Thread(target=keep_backing_up, daemon=True).start()
    try:
        result = fn(*args, **kwargs)
    finally:
        stop.set()
        backup()
        if USE_DRIVE:
            print("backed up to", DRIVE_DIR)
    return result

restored from Drive: ['ogbn-arxiv_sagebn_cross_entropy_balanced_accuracy.db', 'ogbn-arxiv_sagebn_cross_entropy_balanced_accuracy_v3.db', 'ogbn-arxiv_sagebn_cross_entropy_balanced_accuracy_v4.db']

In [4]:
import optuna
import src.node_classification.optuna_search as optuna_search_module
from src.node_classification.optuna_search import run_study
from src.node_classification.ogb_run import run_from_flags

In [ ]:
TARGET_TRIALS = 30

STUDY_NAME = "ogbn-arxiv_sagebn_cross_entropy_balanced_accuracy"

done_so_far = 0
db_path = OPTUNA_DIR / f"{STUDY_NAME}.db"
if db_path.exists():
    existing = optuna.load_study(study_name=STUDY_NAME, storage=f"sqlite:///{db_path}")
    done_so_far = len(existing.trials)
remaining = max(0, TARGET_TRIALS - done_so_far)
print(f"{done_so_far} trial(s) already in the study; running {remaining} more "
      f"to reach {TARGET_TRIALS} total")

# One backup after the search finishes instead; a search of this size is
# short enough that losing it whole to a VM cut is a minor cost, not worth
# risking corruption of the live database to avoid.
if remaining:
    study = run_study(
        dataset="ogbn-arxiv", model="SAGEBN", loss="cross_entropy",
        metric="balanced_accuracy", n_trials=remaining, seeds=(0,),
        epochs=300, early_stop=30, study_name=STUDY_NAME,
    )
    backup()
    if USE_DRIVE:
        print("backed up to", DRIVE_DIR)
else:
    study = optuna.load_study(study_name=STUDY_NAME, storage=f"sqlite:///{db_path}")

0 trial(s) already in the study; running 30 more to reach 30 total
Downloading http://snap.stanford.edu/ogb/data/nodeproppred/arxiv.zip

/usr/local/lib/python3.13/dist-packages/outdated/__init__.py:36: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version
Downloaded 0.08 GB: 100%|██████████| 81/81 [00:03<00:00, 21.89it/s]
Processing...

Extracting /content/pyg-graph-networks/data/arxiv.zip
Loading necessary files...
This might take a while.
Processing graphs...

100%|██████████| 1/1 [00:00<00:00, 11618.57it/s]

Converting graphs into PyG objects...

100%|██████████| 1/1 [00:00<00:00, 331.54it/s]

Saving...

Done!

Optuna search: SAGEBN on ogbn-arxiv  metric=val_balanced_accuracy  loss=cross_entropy  seeds=[0]  device=cuda

[I 2026-09-12 21:29:28,151] A new study created in RDB with name: ogbn-arxiv_sagebn_cross_entropy_balanced_accuracy
[I 2026-09-12 21:29:55,936] Trial 0 finished with value: 0.48474114099924226 and parameters: {'num_layers': 3, 'hidden_channels': 128, 'dropout': 0.30000000000000004, 'lr': 0.008996299860535255, 'optimizer': 'adamw', 'weight_decay': 0.0}. Best is trial 0 with value: 0.48474114099924226.
[I 2026-09-12 21:30:03,739] Trial 1 finished with value: 0.1011118214325202 and parameters: {'num_layers': 2, 'hidden_channels': 512, 'dropout': 0.5, 'lr': 0.01928028441003346, 'optimizer': 'adam', 'weight_decay': 0.01}. Best is trial 0 with value: 0.48474114099924226.
[I 2026-09-12 21:31:02,417] Trial 2 finished with value: 0.48964617527785154 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.35, 'lr': 0.006912670683424534, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 2 with value: 0.48964617527785154.
[I 2026-09-12 21:32:03,470] Trial 3 finished with value: 0.5174355956651537 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.2, 'lr': 0.001550385773372729, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 3 with value: 0.5174355956651537.
[I 2026-09-12 21:32:43,183] Trial 4 finished with value: 0.4951728462224342 and parameters: {'num_layers': 3, 'hidden_channels': 256, 'dropout': 0.15000000000000002, 'lr': 0.0014555846498659243, 'optimizer': 'adam', 'weight_decay': 0.001}. Best is trial 3 with value: 0.5174355956651537.
[I 2026-09-12 21:32:46,989] Trial 5 pruned.
[I 2026-09-12 21:32:52,744] Trial 6 pruned.
[I 2026-09-12 21:32:57,813] Trial 7 pruned.
[I 2026-09-12 21:33:03,407] Trial 8 pruned.
[I 2026-09-12 21:33:08,105] Trial 9 pruned.
[I 2026-09-12 21:33:14,451] Trial 10 pruned.
[I 2026-09-12 21:33:19,183] Trial 11 pruned.
[I 2026-09-12 21:33:25,540] Trial 12 pruned.
[I 2026-09-12 21:33:28,596] Trial 13 pruned.
[I 2026-09-12 21:33:32,451] Trial 14 pruned.
[I 2026-09-12 21:33:36,500] Trial 15 pruned.
[I 2026-09-12 21:33:42,836] Trial 16 pruned.
[I 2026-09-12 21:33:47,234] Trial 17 pruned.
[I 2026-09-12 21:33:50,156] Trial 18 pruned.
[I 2026-09-12 21:33:54,551] Trial 19 pruned.
[I 2026-09-12 21:34:28,335] Trial 20 pruned.
[I 2026-09-12 21:34:34,687] Trial 21 pruned.
[I 2026-09-12 21:34:44,048] Trial 22 pruned.
[I 2026-09-12 21:34:47,937] Trial 23 pruned.
[I 2026-09-12 21:35:41,877] Trial 24 finished with value: 0.5105494639727517 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.2, 'lr': 0.004275526901346672, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 3 with value: 0.5174355956651537.
[I 2026-09-12 21:35:46,550] Trial 25 pruned.
[I 2026-09-12 21:36:00,148] Trial 26 pruned.
[I 2026-09-12 21:36:04,558] Trial 27 pruned.
[I 2026-09-12 21:36:08,400] Trial 28 pruned.
[I 2026-09-12 21:36:14,764] Trial 29 pruned.

Best of 30 trials (6.8 min): val_balanced_accuracy=0.5174 at epoch 171
  num_layers: 3
  hidden_channels: 512
  dropout: 0.2
  lr: 0.001550385773372729
  optimizer: adamw
  weight_decay: 0.0001

Reproduce over all seeds with:
  uv run python -m src.node_classification.ogb_run --dataset ogbn-arxiv --model SAGEBN --loss cross_entropy --num_layers 3 --hidden_channels 512 --dropout 0.20 --lr 1.55e-03 --optimizer adamw --weight_decay 0.0001 --no-dataloader
backed up to /content/drive/MyDrive/GraphNetworks

In [ ]:
print(study.best_trial.params)

{'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.2, 'lr': 0.001550385773372729, 'optimizer': 'adamw', 'weight_decay': 0.0001}

In [ ]:
import pandas as pd

df = study.trials_dataframe()[["number", "value", "params_num_layers", "params_hidden_channels",
                               "params_dropout", "params_lr", "params_optimizer", "params_weight_decay"]]
df = df.rename(columns={"value": "val_balanced_accuracy"})
df

,number,val_balanced_accuracy,params_num_layers,params_hidden_channels,params_dropout,params_lr,params_optimizer,params_weight_decay
0,0,0.484741,3,128,0.30,0.008996,adamw,0.00000
1,1,0.101112,2,512,0.50,0.019280,adam,0.01000
2,2,0.489646,3,512,0.35,0.006913,adamw,0.00010
3,3,0.517436,3,512,0.20,0.001550,adamw,0.00010
4,4,0.495173,3,256,0.15,0.001456,adam,0.00100
5,5,0.073324,3,256,0.50,0.001143,adam,0.01000
6,6,0.293654,3,256,0.40,0.023588,adamw,0.00001
7,7,0.270550,3,256,0.50,0.026380,adamw,0.00050
8,8,0.289251,3,256,0.55,0.007221,adam,0.00010
9,9,0.309478,2,256,0.40,0.004299,adamw,0.00050
10,10,0.208096,3,512,0.60,0.002854,adam,0.00000
11,11,0.253615,3,256,0.15,0.001715,adam,0.00100
12,12,0.220354,3,512,0.15,0.001790,adamw,0.00010
13,13,0.177175,2,256,0.20,0.001249,adam,0.00100
14,14,0.222582,3,256,0.30,0.001871,adamw,0.00010
15,15,0.217367,3,256,0.15,0.004775,adam,0.00100
16,16,0.170801,3,512,0.50,0.001229,adamw,0.00010
17,17,0.166825,2,512,0.25,0.001275,adamw,0.00010
18,18,0.154732,3,128,0.25,0.001914,adam,0.00010
19,19,0.143054,2,512,0.15,0.002804,adam,0.00100
20,20,0.457028,3,512,0.15,0.007740,adamw,0.01000
21,21,0.205875,3,512,0.25,0.001295,adamw,0.01000
22,22,0.288705,3,512,0.30,0.018861,adam,0.00010
23,23,0.220683,3,256,0.25,0.003918,adam,0.00100
24,24,0.510549,3,512,0.20,0.004276,adamw,0.00010
25,25,0.311871,3,128,0.15,0.005193,adamw,0.00010
26,26,0.392194,3,512,0.10,0.003636,adamw,0.00001
27,27,0.186980,2,512,0.10,0.003528,adamw,0.00010
28,28,0.170783,3,256,0.30,0.001205,adam,0.00100
29,29,0.228290,3,512,0.35,0.003015,adamw,0.00050

In [ ]:
# Confirm the search winner over all ten seeds (never report the single
# tuned-seed score). Matches the finished grid's convention: full 500 epochs,
# no early stopping, no scheduler, full batch.
best = study.best_params
flags = (
    f"--dataset ogbn-arxiv --model SAGEBN --loss cross_entropy "
    f"--num_layers {best['num_layers']} --hidden_channels {best['hidden_channels']} "
    f"--dropout {best['dropout']:.2f} --lr {best['lr']:.6f} "
    f"--optimizer {best['optimizer']} --weight_decay {best['weight_decay']:g} "
    f"--epochs 500 --early_stop 30 --no-scheduler --no-dataloader --log_steps 50"
)
print("confirming:", flags)

summary, history = run_with_backup(run_from_flags, flags)

confirming: --dataset ogbn-arxiv --model SAGEBN --loss cross_entropy --num_layers 3 --hidden_channels 512 --dropout 0.20 --lr 0.001550 --optimizer adamw --weight_decay 0.0001 --epochs 500 --early_stop 30 --no-scheduler --no-dataloader --log_steps 50
Namespace(dataset='ogbn-arxiv', model='SAGEBN', num_layers=3, hidden_channels=512, dropout=0.2, heads=8, lr=0.00155, weight_decay=0.0001, optimizer='adamw', epochs=500, early_stop=30, scheduler=False, scheduler_metric='loss', scheduler_threshold=0.005, scheduler_patience=15, loss='cross_entropy', gamma=2.0, weight_power=1.0, dataloader=False, batch_size=1024, fanout=[15, 10], balanced=False, num_workers=0, eval='full', eval_batch_size=4096, log_steps=50, resume=False, seeds=[0, 1, 2, 3, 4, 20, 42, 123, 1234, 12345])
Running SAGEBN on ogbn-arxiv dataset
Device: cuda  Features: 128  Classes: 40

Fresh run: removed 4 old sagebn_cross_entropy_h512 file(s):
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_results.csv
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_history.csv
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_config.json
Seed: 0  |  epoch 050  |  train_loss=1.0196  |  train_acc=0.6938  |  val_loss=1.0043  |  val_acc=0.6941  |  lr=1.55e-03
Seed: 0  |  epoch 100  |  train_loss=0.8646  |  train_acc=0.7304  |  val_loss=0.9050  |  val_acc=0.7181  |  lr=1.55e-03
Seed: 0  |  epoch 150  |  train_loss=0.7640  |  train_acc=0.7557  |  val_loss=0.8738  |  val_acc=0.7261  |  lr=1.55e-03
Early stopping at epoch 177 (no val_loss improvement for 30 epochs)
Completed runs with seed: 0  | best_epoch=147  |  val_loss=0.8710  |  test_acc=0.7138  |  test_f1=0.5142  |  0.9 min
Summary over 1 seed(s): test_acc mean=0.7138  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 1  |  epoch 050  |  train_loss=1.0145  |  train_acc=0.6949  |  val_loss=1.0088  |  val_acc=0.6961  |  lr=1.55e-03
Seed: 1  |  epoch 100  |  train_loss=0.8693  |  train_acc=0.7291  |  val_loss=0.9185  |  val_acc=0.7129  |  lr=1.55e-03
Seed: 1  |  epoch 150  |  train_loss=0.7632  |  train_acc=0.7560  |  val_loss=0.8749  |  val_acc=0.7237  |  lr=1.55e-03
Seed: 1  |  epoch 200  |  train_loss=0.6746  |  train_acc=0.7776  |  val_loss=0.8714  |  val_acc=0.7286  |  lr=1.55e-03
Early stopping at epoch 205 (no val_loss improvement for 30 epochs)
Completed runs with seed: 1  | best_epoch=175  |  val_loss=0.8658  |  test_acc=0.7157  |  test_f1=0.5118  |  1.0 min
Summary over 2 seed(s): test_acc mean=0.7147  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 2  |  epoch 050  |  train_loss=1.0137  |  train_acc=0.6955  |  val_loss=1.0225  |  val_acc=0.6943  |  lr=1.55e-03
Seed: 2  |  epoch 100  |  train_loss=0.8641  |  train_acc=0.7321  |  val_loss=0.9041  |  val_acc=0.7172  |  lr=1.55e-03
Seed: 2  |  epoch 150  |  train_loss=0.7638  |  train_acc=0.7562  |  val_loss=0.8767  |  val_acc=0.7261  |  lr=1.55e-03
Early stopping at epoch 163 (no val_loss improvement for 30 epochs)
Completed runs with seed: 2  | best_epoch=133  |  val_loss=0.8692  |  test_acc=0.7164  |  test_f1=0.5044  |  0.8 min
Summary over 3 seed(s): test_acc mean=0.7153  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 3  |  epoch 050  |  train_loss=1.0170  |  train_acc=0.6943  |  val_loss=1.0040  |  val_acc=0.6939  |  lr=1.55e-03
Seed: 3  |  epoch 100  |  train_loss=0.8710  |  train_acc=0.7292  |  val_loss=0.9059  |  val_acc=0.7173  |  lr=1.55e-03
Seed: 3  |  epoch 150  |  train_loss=0.7639  |  train_acc=0.7561  |  val_loss=0.8749  |  val_acc=0.7254  |  lr=1.55e-03
Early stopping at epoch 199 (no val_loss improvement for 30 epochs)
Completed runs with seed: 3  | best_epoch=169  |  val_loss=0.8640  |  test_acc=0.7205  |  test_f1=0.5082  |  1.0 min
Summary over 4 seed(s): test_acc mean=0.7166  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 4  |  epoch 050  |  train_loss=1.0190  |  train_acc=0.6946  |  val_loss=1.0314  |  val_acc=0.6875  |  lr=1.55e-03
Seed: 4  |  epoch 100  |  train_loss=0.8729  |  train_acc=0.7297  |  val_loss=0.9099  |  val_acc=0.7159  |  lr=1.55e-03
Seed: 4  |  epoch 150  |  train_loss=0.7632  |  train_acc=0.7558  |  val_loss=0.8825  |  val_acc=0.7254  |  lr=1.55e-03
Seed: 4  |  epoch 200  |  train_loss=0.6790  |  train_acc=0.7765  |  val_loss=0.8877  |  val_acc=0.7258  |  lr=1.55e-03
Early stopping at epoch 214 (no val_loss improvement for 30 epochs)
Completed runs with seed: 4  | best_epoch=184  |  val_loss=0.8641  |  test_acc=0.7175  |  test_f1=0.5144  |  1.1 min
Summary over 5 seed(s): test_acc mean=0.7168  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 20  |  epoch 050  |  train_loss=1.0115  |  train_acc=0.6974  |  val_loss=1.0286  |  val_acc=0.6941  |  lr=1.55e-03
Seed: 20  |  epoch 100  |  train_loss=0.8578  |  train_acc=0.7338  |  val_loss=0.9110  |  val_acc=0.7173  |  lr=1.55e-03
Seed: 20  |  epoch 150  |  train_loss=0.7578  |  train_acc=0.7567  |  val_loss=0.8772  |  val_acc=0.7249  |  lr=1.55e-03
Early stopping at epoch 177 (no val_loss improvement for 30 epochs)
Completed runs with seed: 20  | best_epoch=147  |  val_loss=0.8733  |  test_acc=0.7145  |  test_f1=0.5052  |  0.9 min
Summary over 6 seed(s): test_acc mean=0.7164  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 42  |  epoch 050  |  train_loss=1.0102  |  train_acc=0.6965  |  val_loss=1.0459  |  val_acc=0.6840  |  lr=1.55e-03
Seed: 42  |  epoch 100  |  train_loss=0.8636  |  train_acc=0.7323  |  val_loss=0.8914  |  val_acc=0.7223  |  lr=1.55e-03
Seed: 42  |  epoch 150  |  train_loss=0.7637  |  train_acc=0.7556  |  val_loss=0.8901  |  val_acc=0.7235  |  lr=1.55e-03
Early stopping at epoch 185 (no val_loss improvement for 30 epochs)
Completed runs with seed: 42  | best_epoch=155  |  val_loss=0.8688  |  test_acc=0.7200  |  test_f1=0.5088  |  1.0 min
Summary over 7 seed(s): test_acc mean=0.7169  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 123  |  epoch 050  |  train_loss=1.0133  |  train_acc=0.6965  |  val_loss=0.9963  |  val_acc=0.6967  |  lr=1.55e-03
Seed: 123  |  epoch 100  |  train_loss=0.8675  |  train_acc=0.7304  |  val_loss=0.8998  |  val_acc=0.7180  |  lr=1.55e-03
Seed: 123  |  epoch 150  |  train_loss=0.7627  |  train_acc=0.7563  |  val_loss=0.8813  |  val_acc=0.7246  |  lr=1.55e-03
Seed: 123  |  epoch 200  |  train_loss=0.6720  |  train_acc=0.7779  |  val_loss=0.8853  |  val_acc=0.7275  |  lr=1.55e-03
Early stopping at epoch 202 (no val_loss improvement for 30 epochs)
Completed runs with seed: 123  | best_epoch=172  |  val_loss=0.8660  |  test_acc=0.7201  |  test_f1=0.5123  |  1.0 min
Summary over 8 seed(s): test_acc mean=0.7173  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 1234  |  epoch 050  |  train_loss=1.0144  |  train_acc=0.6949  |  val_loss=1.0273  |  val_acc=0.6877  |  lr=1.55e-03
Seed: 1234  |  epoch 100  |  train_loss=0.8654  |  train_acc=0.7315  |  val_loss=0.9221  |  val_acc=0.7169  |  lr=1.55e-03
Seed: 1234  |  epoch 150  |  train_loss=0.7601  |  train_acc=0.7563  |  val_loss=0.8666  |  val_acc=0.7296  |  lr=1.55e-03
Early stopping at epoch 179 (no val_loss improvement for 30 epochs)
Completed runs with seed: 1234  | best_epoch=149  |  val_loss=0.8662  |  test_acc=0.7201  |  test_f1=0.5122  |  0.9 min
Summary over 9 seed(s): test_acc mean=0.7176  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Seed: 12345  |  epoch 050  |  train_loss=1.0161  |  train_acc=0.6942  |  val_loss=1.0094  |  val_acc=0.6952  |  lr=1.55e-03
Seed: 12345  |  epoch 100  |  train_loss=0.8672  |  train_acc=0.7308  |  val_loss=0.8939  |  val_acc=0.7233  |  lr=1.55e-03
Seed: 12345  |  epoch 150  |  train_loss=0.7624  |  train_acc=0.7557  |  val_loss=0.8752  |  val_acc=0.7288  |  lr=1.55e-03
Early stopping at epoch 163 (no val_loss improvement for 30 epochs)
Completed runs with seed: 12345  | best_epoch=133  |  val_loss=0.8723  |  test_acc=0.7162  |  test_f1=0.4980  |  0.8 min
Summary over 10 seed(s): test_acc mean=0.7175  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_cross_entropy_h512_summary.csv
====================================================================================================
Run sagebn_cross_entropy_h512 finished: 10 seeds, 9.6 min this session, 9.6 min of training in total
backed up to /content/drive/MyDrive/GraphNetworks

In [ ]:
print(summary)

                            mean       std    ci_low   ci_high
Test loss               0.909202  0.005177  0.905498  0.912906
Test acc                0.717470  0.002524  0.715664  0.719276
Test precision          0.585482  0.009185  0.578911  0.592052
Test recall             0.495927  0.007115  0.490838  0.501017
Test f1                 0.508954  0.005182  0.505247  0.512661
Test balanced_accuracy  0.495927  0.007115  0.490838  0.501017
Test brier              0.201442  0.001425  0.200422  0.202461
Test roc_auc            0.971947  0.000882  0.971316  0.972578
Test avg_precision      0.550513  0.004025  0.547634  0.553392
Test ece                0.036691  0.006339  0.032156  0.041225

In [5]:
import subprocess, importlib

In [6]:
# pull the fixed file onto disk (only needed if running in Colab, which cloned separately)
if IN_COLAB:
    subprocess.run(["git", "-C", str(ROOT), "pull", "--ff-only"], check=True)

importlib.reload(optuna_search_module)
print("reloaded, has weight_power fix:",
      "weight_power=1.0" in Path(optuna_search_module.__file__).read_text())

reloaded, has weight_power fix: False

In [7]:
TARGET_TRIALS = 30
STUDY_NAME_WCE = "ogbn-arxiv_sagebn_weighted_cross_entropy_balanced_accuracy"

done_so_far = 0
db_path = OPTUNA_DIR / f"{STUDY_NAME_WCE}.db"
if db_path.exists():
    existing = optuna.load_study(study_name=STUDY_NAME_WCE, storage=f"sqlite:///{db_path}")
    done_so_far = len(existing.trials)
remaining = max(0, TARGET_TRIALS - done_so_far)
print(f"{done_so_far} trial(s) already in the study; running {remaining} more "
      f"to reach {TARGET_TRIALS} total")

if remaining:
    study_wce = run_study(
    dataset="ogbn-arxiv", model="SAGEBN", loss="weighted_ce",
    metric="balanced_accuracy", seeds=(0,), n_trials=remaining,
    epochs=300, early_stop=30, study_name=STUDY_NAME_WCE)
    backup()
    if USE_DRIVE:
        print("backed up to", DRIVE_DIR)
else:
    study_wce = optuna.load_study(study_name=STUDY_NAME_WCE, storage=f"sqlite:///{db_path}")

0 trial(s) already in the study; running 30 more to reach 30 total

/usr/local/lib/python3.13/dist-packages/outdated/__init__.py:36: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

Downloading http://snap.stanford.edu/ogb/data/nodeproppred/arxiv.zip

Downloaded 0.08 GB: 100%|██████████| 81/81 [00:46<00:00,  1.74it/s]
Processing...

Extracting /content/pyg-graph-networks/data/arxiv.zip
Loading necessary files...
This might take a while.
Processing graphs...

100%|██████████| 1/1 [00:00<00:00, 13400.33it/s]

Converting graphs into PyG objects...

100%|██████████| 1/1 [00:00<00:00, 336.08it/s]

Saving...

Done!

Optuna search: SAGEBN on ogbn-arxiv  metric=val_balanced_accuracy  loss=weighted_ce  seeds=[0]  device=cuda

[I 2026-09-12 23:07:15,490] A new study created in RDB with name: ogbn-arxiv_sagebn_weighted_cross_entropy_balanced_accuracy
[I 2026-09-12 23:07:54,217] Trial 0 finished with value: 0.5842359674585135 and parameters: {'num_layers': 3, 'hidden_channels': 128, 'dropout': 0.30000000000000004, 'lr': 0.008996299860535255, 'optimizer': 'adamw', 'weight_decay': 0.0}. Best is trial 0 with value: 0.5842359674585135.
[I 2026-09-12 23:08:12,074] Trial 1 finished with value: 0.19434127371506668 and parameters: {'num_layers': 2, 'hidden_channels': 512, 'dropout': 0.5, 'lr': 0.01928028441003346, 'optimizer': 'adam', 'weight_decay': 0.01}. Best is trial 0 with value: 0.5842359674585135.
[I 2026-09-12 23:09:57,892] Trial 2 finished with value: 0.5749697839630349 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.35, 'lr': 0.006912670683424534, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 0 with value: 0.5842359674585135.
[I 2026-09-12 23:11:37,622] Trial 3 finished with value: 0.5775576014160638 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.2, 'lr': 0.001550385773372729, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 0 with value: 0.5842359674585135.
[I 2026-09-12 23:12:30,912] Trial 4 finished with value: 0.5618090143041015 and parameters: {'num_layers': 3, 'hidden_channels': 256, 'dropout': 0.15000000000000002, 'lr': 0.0014555846498659243, 'optimizer': 'adam', 'weight_decay': 0.001}. Best is trial 0 with value: 0.5842359674585135.
[I 2026-09-12 23:12:39,725] Trial 5 pruned.
[I 2026-09-12 23:12:58,040] Trial 6 pruned.
[I 2026-09-12 23:13:11,545] Trial 7 pruned.
[I 2026-09-12 23:13:29,338] Trial 8 pruned.
[I 2026-09-12 23:13:42,228] Trial 9 pruned.
[I 2026-09-12 23:13:46,411] Trial 10 pruned.
[I 2026-09-12 23:14:03,072] Trial 11 pruned.
[I 2026-09-12 23:14:26,560] Trial 12 pruned.
[I 2026-09-12 23:14:32,058] Trial 13 pruned.
[I 2026-09-12 23:15:09,911] Trial 14 pruned.
[I 2026-09-12 23:15:20,235] Trial 15 pruned.
[I 2026-09-12 23:15:36,852] Trial 16 pruned.
[I 2026-09-12 23:16:03,228] Trial 17 pruned.
[I 2026-09-12 23:16:08,746] Trial 18 pruned.
[I 2026-09-12 23:16:25,358] Trial 19 pruned.
[I 2026-09-12 23:16:30,863] Trial 20 pruned.
[I 2026-09-12 23:17:00,542] Trial 21 pruned.
[I 2026-09-12 23:17:32,612] Trial 22 pruned.
[I 2026-09-12 23:17:53,821] Trial 23 pruned.
[I 2026-09-12 23:18:25,053] Trial 24 pruned.
[I 2026-09-12 23:18:31,636] Trial 25 pruned.
[I 2026-09-12 23:18:48,167] Trial 26 pruned.
[I 2026-09-12 23:18:57,068] Trial 27 pruned.
[I 2026-09-12 23:19:08,853] Trial 28 pruned.
[I 2026-09-12 23:19:20,115] Trial 29 pruned.

Best of 30 trials (12.1 min): val_balanced_accuracy=0.5842 at epoch 114
  num_layers: 3
  hidden_channels: 128
  dropout: 0.30000000000000004
  lr: 0.008996299860535255
  optimizer: adamw
  weight_decay: 0.0

Reproduce over all seeds with:
  uv run python -m src.node_classification.ogb_run --dataset ogbn-arxiv --model SAGEBN --loss weighted_ce --num_layers 3 --hidden_channels 128 --dropout 0.30 --lr 9.00e-03 --optimizer adamw --weight_decay 0 --no-dataloader
backed up to /content/drive/MyDrive/GraphNetworks

In [8]:
print(study_wce.best_trial.params)

{'num_layers': 3, 'hidden_channels': 128, 'dropout': 0.30000000000000004, 'lr': 0.008996299860535255, 'optimizer': 'adamw', 'weight_decay': 0.0}

In [10]:
import pandas as pd

df2 = study_wce.trials_dataframe()[["number", "value", "params_num_layers", "params_hidden_channels",
                               "params_dropout", "params_lr", "params_optimizer", "params_weight_decay"]]
df2 = df2.rename(columns={"value": "val_balanced_accuracy"})
df2

,number,val_balanced_accuracy,params_num_layers,params_hidden_channels,params_dropout,params_lr,params_optimizer,params_weight_decay
0,0,0.584236,3,128,0.30,0.008996,adamw,0.00000
1,1,0.194341,2,512,0.50,0.019280,adam,0.01000
2,2,0.574970,3,512,0.35,0.006913,adamw,0.00010
3,3,0.577558,3,512,0.20,0.001550,adamw,0.00010
4,4,0.561809,3,256,0.15,0.001456,adam,0.00100
5,5,0.182681,3,256,0.50,0.001143,adam,0.01000
6,6,0.532659,3,256,0.40,0.023588,adamw,0.00001
7,7,0.491336,3,256,0.50,0.026380,adamw,0.00050
8,8,0.522796,3,256,0.55,0.007221,adam,0.00010
9,9,0.524510,2,256,0.40,0.004299,adamw,0.00050
10,10,0.391170,2,128,0.55,0.005104,adamw,0.00000
11,11,0.290844,3,512,0.15,0.002478,adamw,0.00010
12,12,0.556580,3,128,0.30,0.013461,adamw,0.00000
13,13,0.256074,3,128,0.25,0.001414,adamw,0.00000
14,14,0.532751,3,512,0.15,0.017657,adamw,0.00050
15,15,0.340074,2,512,0.10,0.005174,adamw,0.00100
16,16,0.362010,3,512,0.25,0.001005,adamw,0.00001
17,17,0.498950,3,512,0.35,0.002940,adam,0.00010
18,18,0.351364,3,128,0.25,0.002998,adamw,0.00010
19,19,0.403151,3,512,0.40,0.001577,adamw,0.00010
20,20,0.334035,3,128,0.45,0.002782,adamw,0.00000
21,21,0.511442,3,512,0.25,0.005817,adamw,0.00010
22,22,0.513839,3,512,0.40,0.009295,adamw,0.01000
23,23,0.532362,2,512,0.30,0.011043,adamw,0.00010
24,24,0.516467,3,512,0.50,0.004358,adamw,0.00000
25,25,0.435110,3,128,0.10,0.007728,adamw,0.00010
26,26,0.275939,3,512,0.45,0.028331,adam,0.00010
27,27,0.505623,3,128,0.45,0.006866,adamw,0.00000
28,28,0.429278,2,512,0.30,0.004026,adamw,0.00010
29,29,0.525517,3,128,0.15,0.027568,adamw,0.00010

In [12]:
# Confirm the weighted_ce search winner over all ten seeds.
best_wce = study_wce.best_params
flags_wce = (
    f"--dataset ogbn-arxiv --model SAGEBN --loss weighted_ce "
    f"--num_layers {best_wce['num_layers']} --hidden_channels {best_wce['hidden_channels']} "
    f"--dropout {best_wce['dropout']:.2f} --lr {best_wce['lr']:.6f} "
    f"--optimizer {best_wce['optimizer']} --weight_decay {best_wce['weight_decay']:g} "
    f"--epochs 500 --early_stop 30 --no-scheduler --no-dataloader --log_steps 50"
)
print("confirming:", flags_wce)

summary_wce, history_wce = run_with_backup(run_from_flags, flags_wce)

confirming: --dataset ogbn-arxiv --model SAGEBN --loss weighted_ce --num_layers 3 --hidden_channels 128 --dropout 0.30 --lr 0.008996 --optimizer adamw --weight_decay 0 --epochs 500 --early_stop 30 --no-scheduler --no-dataloader --log_steps 50
Namespace(dataset='ogbn-arxiv', model='SAGEBN', num_layers=3, hidden_channels=128, dropout=0.3, heads=8, lr=0.008996, weight_decay=0.0, optimizer='adamw', epochs=500, early_stop=30, scheduler=False, scheduler_metric='loss', scheduler_threshold=0.005, scheduler_patience=15, loss='weighted_ce', gamma=2.0, weight_power=1.0, dataloader=False, batch_size=1024, fanout=[15, 10], balanced=False, num_workers=0, eval='full', eval_batch_size=4096, log_steps=50, resume=False, seeds=[0, 1, 2, 3, 4, 20, 42, 123, 1234, 12345])
Running SAGEBN on ogbn-arxiv dataset
Device: cuda  Features: 128  Classes: 40

Fresh run: removed 4 old sagebn_weighted_ce_h128 file(s):
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_results.csv
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_history.csv
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
  /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_config.json
Seed: 0  |  epoch 050  |  train_loss=1.4709  |  train_acc=0.5639  |  val_loss=1.4290  |  val_acc=0.6138  |  lr=9.00e-03
Seed: 0  |  epoch 100  |  train_loss=1.3081  |  train_acc=0.5873  |  val_loss=1.3317  |  val_acc=0.6069  |  lr=9.00e-03
Early stopping at epoch 124 (no val_loss improvement for 30 epochs)
Completed runs with seed: 0  | best_epoch=94  |  val_loss=1.3019  |  test_acc=0.6107  |  test_f1=0.4541  |  0.5 min
Summary over 1 seed(s): test_acc mean=0.6107  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 1  |  epoch 050  |  train_loss=1.4760  |  train_acc=0.5564  |  val_loss=1.4235  |  val_acc=0.5969  |  lr=9.00e-03
Seed: 1  |  epoch 100  |  train_loss=1.3103  |  train_acc=0.5877  |  val_loss=1.3459  |  val_acc=0.6364  |  lr=9.00e-03
Early stopping at epoch 121 (no val_loss improvement for 30 epochs)
Completed runs with seed: 1  | best_epoch=91  |  val_loss=1.2987  |  test_acc=0.6103  |  test_f1=0.4632  |  0.5 min
Summary over 2 seed(s): test_acc mean=0.6105  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 2  |  epoch 050  |  train_loss=1.4784  |  train_acc=0.5649  |  val_loss=1.4149  |  val_acc=0.6048  |  lr=9.00e-03
Seed: 2  |  epoch 100  |  train_loss=1.3091  |  train_acc=0.5924  |  val_loss=1.3357  |  val_acc=0.6260  |  lr=9.00e-03
Early stopping at epoch 127 (no val_loss improvement for 30 epochs)
Completed runs with seed: 2  | best_epoch=97  |  val_loss=1.3280  |  test_acc=0.6217  |  test_f1=0.4641  |  0.5 min
Summary over 3 seed(s): test_acc mean=0.6142  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 3  |  epoch 050  |  train_loss=1.4736  |  train_acc=0.5614  |  val_loss=1.4014  |  val_acc=0.5861  |  lr=9.00e-03
Seed: 3  |  epoch 100  |  train_loss=1.3027  |  train_acc=0.5844  |  val_loss=1.3531  |  val_acc=0.6128  |  lr=9.00e-03
Early stopping at epoch 109 (no val_loss improvement for 30 epochs)
Completed runs with seed: 3  | best_epoch=79  |  val_loss=1.3314  |  test_acc=0.6093  |  test_f1=0.4486  |  0.5 min
Summary over 4 seed(s): test_acc mean=0.6130  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 4  |  epoch 050  |  train_loss=1.4867  |  train_acc=0.5602  |  val_loss=1.4030  |  val_acc=0.5806  |  lr=9.00e-03
Seed: 4  |  epoch 100  |  train_loss=1.3072  |  train_acc=0.5870  |  val_loss=1.3619  |  val_acc=0.6318  |  lr=9.00e-03
Early stopping at epoch 119 (no val_loss improvement for 30 epochs)
Completed runs with seed: 4  | best_epoch=89  |  val_loss=1.3341  |  test_acc=0.6144  |  test_f1=0.4602  |  0.5 min
Summary over 5 seed(s): test_acc mean=0.6133  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 20  |  epoch 050  |  train_loss=1.4735  |  train_acc=0.5617  |  val_loss=1.3689  |  val_acc=0.5953  |  lr=9.00e-03
Seed: 20  |  epoch 100  |  train_loss=1.3116  |  train_acc=0.5865  |  val_loss=1.3816  |  val_acc=0.6346  |  lr=9.00e-03
Early stopping at epoch 138 (no val_loss improvement for 30 epochs)
Completed runs with seed: 20  | best_epoch=108  |  val_loss=1.2994  |  test_acc=0.5951  |  test_f1=0.4518  |  0.6 min
Summary over 6 seed(s): test_acc mean=0.6103  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 42  |  epoch 050  |  train_loss=1.4643  |  train_acc=0.5635  |  val_loss=1.4294  |  val_acc=0.5730  |  lr=9.00e-03
Seed: 42  |  epoch 100  |  train_loss=1.3068  |  train_acc=0.5912  |  val_loss=1.3475  |  val_acc=0.6198  |  lr=9.00e-03
Early stopping at epoch 100 (no val_loss improvement for 30 epochs)
Completed runs with seed: 42  | best_epoch=70  |  val_loss=1.3334  |  test_acc=0.6064  |  test_f1=0.4464  |  0.4 min
Summary over 7 seed(s): test_acc mean=0.6097  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 123  |  epoch 050  |  train_loss=1.4755  |  train_acc=0.5653  |  val_loss=1.4092  |  val_acc=0.6188  |  lr=9.00e-03
Seed: 123  |  epoch 100  |  train_loss=1.2998  |  train_acc=0.5891  |  val_loss=1.3915  |  val_acc=0.6220  |  lr=9.00e-03
Early stopping at epoch 111 (no val_loss improvement for 30 epochs)
Completed runs with seed: 123  | best_epoch=81  |  val_loss=1.3297  |  test_acc=0.5968  |  test_f1=0.4474  |  0.5 min
Summary over 8 seed(s): test_acc mean=0.6081  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 1234  |  epoch 050  |  train_loss=1.4810  |  train_acc=0.5580  |  val_loss=1.4257  |  val_acc=0.5924  |  lr=9.00e-03
Seed: 1234  |  epoch 100  |  train_loss=1.3140  |  train_acc=0.5880  |  val_loss=1.3427  |  val_acc=0.6116  |  lr=9.00e-03
Early stopping at epoch 106 (no val_loss improvement for 30 epochs)
Completed runs with seed: 1234  | best_epoch=76  |  val_loss=1.3306  |  test_acc=0.6192  |  test_f1=0.4482  |  0.5 min
Summary over 9 seed(s): test_acc mean=0.6093  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Seed: 12345  |  epoch 050  |  train_loss=1.4779  |  train_acc=0.5642  |  val_loss=1.3742  |  val_acc=0.5867  |  lr=9.00e-03
Early stopping at epoch 91 (no val_loss improvement for 30 epochs)
Completed runs with seed: 12345  | best_epoch=61  |  val_loss=1.3369  |  test_acc=0.6064  |  test_f1=0.4494  |  0.4 min
Summary over 10 seed(s): test_acc mean=0.6090  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_h128_summary.csv
====================================================================================================
Run sagebn_weighted_ce_h128 finished: 10 seeds, 5.0 min this session, 5.0 min of training in total
backed up to /content/drive/MyDrive/GraphNetworks

In [13]:
print(summary_wce)

                            mean       std    ci_low   ci_high
Test loss               1.453618  0.013064  1.444273  1.462964
Test acc                0.609034  0.008520  0.602939  0.615129
Test precision          0.436140  0.006100  0.431777  0.440504
Test recall             0.552863  0.007793  0.547288  0.558438
Test f1                 0.453338  0.006749  0.448510  0.458166
Test balanced_accuracy  0.552863  0.007793  0.547288  0.558438
Test brier              0.268104  0.004783  0.264682  0.271525
Test roc_auc            0.961331  0.001084  0.960555  0.962106
Test avg_precision      0.488132  0.004402  0.484983  0.491281
Test ece                0.024928  0.007452  0.019597  0.030258

In [14]:
TARGET_TRIALS = 30
STUDY_NAME_WCE_P = "ogbn-arxiv_sagebn_weighted_cross_entropy_balanced_accuracy_p0.5"

done_so_far = 0
db_path = OPTUNA_DIR / f"{STUDY_NAME_WCE_P}.db"
if db_path.exists():
    existing = optuna.load_study(study_name=STUDY_NAME_WCE_P, storage=f"sqlite:///{db_path}")
    done_so_far = len(existing.trials)
remaining = max(0, TARGET_TRIALS - done_so_far)
print(f"{done_so_far} trial(s) already in the study; running {remaining} more "
      f"to reach {TARGET_TRIALS} total")

if remaining:
    study_wce_p05 = run_study(
    dataset="ogbn-arxiv", model="SAGEBN", loss="weighted_ce",
    metric="balanced_accuracy", seeds=(0,), n_trials=remaining,
    epochs=300, weight_power=0.5, early_stop=30, study_name=STUDY_NAME_WCE_P)
    backup()
    if USE_DRIVE:
        print("backed up to", DRIVE_DIR)
else:
    study_wce_p05 = optuna.load_study(study_name=STUDY_NAME_WCE_P, storage=f"sqlite:///{db_path}")

0 trial(s) already in the study; running 30 more to reach 30 total

[I 2026-09-12 23:38:44,101] A new study created in RDB with name: ogbn-arxiv_sagebn_weighted_cross_entropy_balanced_accuracy_p0.5

Optuna search: SAGEBN on ogbn-arxiv  metric=val_balanced_accuracy  loss=weighted_ce  seeds=[0]  device=cuda

[I 2026-09-12 23:39:38,083] Trial 0 finished with value: 0.5671274200113621 and parameters: {'num_layers': 3, 'hidden_channels': 128, 'dropout': 0.30000000000000004, 'lr': 0.008996299860535255, 'optimizer': 'adamw', 'weight_decay': 0.0}. Best is trial 0 with value: 0.5671274200113621.
[I 2026-09-12 23:39:55,764] Trial 1 finished with value: 0.0996605957617123 and parameters: {'num_layers': 2, 'hidden_channels': 512, 'dropout': 0.5, 'lr': 0.01928028441003346, 'optimizer': 'adam', 'weight_decay': 0.01}. Best is trial 0 with value: 0.5671274200113621.
[I 2026-09-12 23:41:43,564] Trial 2 finished with value: 0.5537634820431705 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.35, 'lr': 0.006912670683424534, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 0 with value: 0.5671274200113621.
[I 2026-09-12 23:43:33,924] Trial 3 finished with value: 0.5627688447802135 and parameters: {'num_layers': 3, 'hidden_channels': 512, 'dropout': 0.2, 'lr': 0.001550385773372729, 'optimizer': 'adamw', 'weight_decay': 0.0001}. Best is trial 0 with value: 0.5671274200113621.
[I 2026-09-12 23:44:53,371] Trial 4 finished with value: 0.5507338710198055 and parameters: {'num_layers': 3, 'hidden_channels': 256, 'dropout': 0.15000000000000002, 'lr': 0.0014555846498659243, 'optimizer': 'adam', 'weight_decay': 0.001}. Best is trial 0 with value: 0.5671274200113621.
[I 2026-09-12 23:45:02,165] Trial 5 pruned.
[I 2026-09-12 23:45:20,377] Trial 6 pruned.
[I 2026-09-12 23:45:30,064] Trial 7 pruned.
[I 2026-09-12 23:45:45,743] Trial 8 pruned.
[I 2026-09-12 23:45:56,665] Trial 9 pruned.
[I 2026-09-12 23:46:00,857] Trial 10 pruned.
[I 2026-09-12 23:46:24,059] Trial 11 pruned.
[I 2026-09-12 23:46:38,978] Trial 12 pruned.
[I 2026-09-12 23:46:44,462] Trial 13 pruned.
[I 2026-09-12 23:47:20,670] Trial 14 pruned.
[I 2026-09-12 23:47:30,975] Trial 15 pruned.
[I 2026-09-12 23:47:47,594] Trial 16 pruned.
[I 2026-09-12 23:48:14,774] Trial 17 pruned.
[I 2026-09-12 23:48:20,306] Trial 18 pruned.
[I 2026-09-12 23:48:36,917] Trial 19 pruned.
[I 2026-09-12 23:48:42,413] Trial 20 pruned.
[I 2026-09-12 23:49:11,283] Trial 21 pruned.
[I 2026-09-12 23:49:52,310] Trial 22 pruned.
[I 2026-09-12 23:50:29,934] Trial 23 pruned.
[I 2026-09-12 23:50:59,526] Trial 24 pruned.
[I 2026-09-12 23:51:11,570] Trial 25 pruned.
[I 2026-09-12 23:51:28,117] Trial 26 pruned.
[I 2026-09-12 23:51:33,623] Trial 27 pruned.
[I 2026-09-12 23:51:43,910] Trial 28 pruned.
[I 2026-09-12 23:52:03,490] Trial 29 pruned.

Best of 30 trials (13.3 min): val_balanced_accuracy=0.5671 at epoch 177
  num_layers: 3
  hidden_channels: 128
  dropout: 0.30000000000000004
  lr: 0.008996299860535255
  optimizer: adamw
  weight_decay: 0.0

Reproduce over all seeds with:
  uv run python -m src.node_classification.ogb_run --dataset ogbn-arxiv --model SAGEBN --loss weighted_ce --num_layers 3 --hidden_channels 128 --dropout 0.30 --lr 9.00e-03 --optimizer adamw --weight_decay 0 --no-dataloader --weight_power 0.5
backed up to /content/drive/MyDrive/GraphNetworks

In [15]:
print(study_wce_p05.best_trial.params)

{'num_layers': 3, 'hidden_channels': 128, 'dropout': 0.30000000000000004, 'lr': 0.008996299860535255, 'optimizer': 'adamw', 'weight_decay': 0.0}

In [16]:
import pandas as pd

df3 = study_wce_p05.trials_dataframe()[["number", "value", "params_num_layers", "params_hidden_channels",
                               "params_dropout", "params_lr", "params_optimizer", "params_weight_decay"]]
df3 = df3.rename(columns={"value": "val_balanced_accuracy"})
df3

,number,val_balanced_accuracy,params_num_layers,params_hidden_channels,params_dropout,params_lr,params_optimizer,params_weight_decay
0,0,0.567127,3,128,0.30,0.008996,adamw,0.00000
1,1,0.099661,2,512,0.50,0.019280,adam,0.01000
2,2,0.553763,3,512,0.35,0.006913,adamw,0.00010
3,3,0.562769,3,512,0.20,0.001550,adamw,0.00010
4,4,0.550734,3,256,0.15,0.001456,adam,0.00100
5,5,0.115319,3,256,0.50,0.001143,adam,0.01000
6,6,0.471304,3,256,0.40,0.023588,adamw,0.00001
7,7,0.335744,3,256,0.50,0.026380,adamw,0.00050
8,8,0.447733,3,256,0.55,0.007221,adam,0.00010
9,9,0.460967,2,256,0.40,0.004299,adamw,0.00050
10,10,0.257916,2,128,0.55,0.005104,adamw,0.00000
11,11,0.406188,3,512,0.15,0.002478,adamw,0.00010
12,12,0.502807,3,128,0.30,0.013461,adamw,0.00000
13,13,0.184142,3,128,0.25,0.001414,adamw,0.00000
14,14,0.478338,3,512,0.15,0.017657,adamw,0.00050
15,15,0.258834,2,512,0.10,0.005174,adamw,0.00100
16,16,0.284462,3,512,0.25,0.001005,adamw,0.00001
17,17,0.434176,3,512,0.35,0.002940,adam,0.00010
18,18,0.257877,3,128,0.25,0.002998,adamw,0.00010
19,19,0.321726,3,512,0.40,0.001577,adamw,0.00010
20,20,0.219569,3,128,0.45,0.002782,adamw,0.00000
21,21,0.442002,3,512,0.25,0.005817,adamw,0.00010
22,22,0.494420,3,512,0.40,0.009295,adamw,0.01000
23,23,0.521576,2,512,0.30,0.011043,adamw,0.00010
24,24,0.455534,3,512,0.50,0.004358,adamw,0.00000
25,25,0.481439,3,128,0.10,0.007728,adamw,0.00010
26,26,0.233834,3,512,0.45,0.028331,adam,0.00010
27,27,0.322369,3,128,0.45,0.006866,adamw,0.00000
28,28,0.293402,2,512,0.30,0.004026,adamw,0.00010
29,29,0.515843,3,128,0.15,0.027568,adamw,0.00010

In [17]:
# Confirm the weighted_ce search winner over all ten seeds.

best_wce_p05 = study_wce_p05.best_params
flags_wce_p05 = (
    f"--dataset ogbn-arxiv --model SAGEBN --loss weighted_ce --weight_power 0.5 "
    f"--num_layers {best_wce_p05['num_layers']} --hidden_channels {best_wce_p05['hidden_channels']} "
    f"--dropout {best_wce_p05['dropout']:.2f} --lr {best_wce_p05['lr']:.6f} "
    f"--optimizer {best_wce_p05['optimizer']} --weight_decay {best_wce_p05['weight_decay']:g} "
    f"--epochs 500 --early_stop 30 --no-scheduler --no-dataloader --log_steps 50"
)
print("confirming:", flags_wce_p05)

summary_wce_p05, history_wce_p05 = run_with_backup(run_from_flags, flags_wce_p05)

confirming: --dataset ogbn-arxiv --model SAGEBN --loss weighted_ce --weight_power 0.5 --num_layers 3 --hidden_channels 128 --dropout 0.30 --lr 0.008996 --optimizer adamw --weight_decay 0 --epochs 500 --early_stop 30 --no-scheduler --no-dataloader --log_steps 50
Namespace(dataset='ogbn-arxiv', model='SAGEBN', num_layers=3, hidden_channels=128, dropout=0.3, heads=8, lr=0.008996, weight_decay=0.0, optimizer='adamw', epochs=500, early_stop=30, scheduler=False, scheduler_metric='loss', scheduler_threshold=0.005, scheduler_patience=15, loss='weighted_ce', gamma=2.0, weight_power=0.5, dataloader=False, batch_size=1024, fanout=[15, 10], balanced=False, num_workers=0, eval='full', eval_batch_size=4096, log_steps=50, resume=False, seeds=[0, 1, 2, 3, 4, 20, 42, 123, 1234, 12345])
Running SAGEBN on ogbn-arxiv dataset
Device: cuda  Features: 128  Classes: 40

Seed: 0  |  epoch 050  |  train_loss=1.4027  |  train_acc=0.6526  |  val_loss=1.3086  |  val_acc=0.6870  |  lr=9.00e-03
Seed: 0  |  epoch 100  |  train_loss=1.2702  |  train_acc=0.6737  |  val_loss=1.1889  |  val_acc=0.6905  |  lr=9.00e-03
Seed: 0  |  epoch 150  |  train_loss=1.1976  |  train_acc=0.6837  |  val_loss=1.1535  |  val_acc=0.6907  |  lr=9.00e-03
Early stopping at epoch 156 (no val_loss improvement for 30 epochs)
Completed runs with seed: 0  | best_epoch=126  |  val_loss=1.1323  |  test_acc=0.6818  |  test_f1=0.4965  |  0.7 min
Summary over 1 seed(s): test_acc mean=0.6818  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 1  |  epoch 050  |  train_loss=1.4069  |  train_acc=0.6501  |  val_loss=1.2568  |  val_acc=0.6865  |  lr=9.00e-03
Seed: 1  |  epoch 100  |  train_loss=1.2604  |  train_acc=0.6763  |  val_loss=1.1654  |  val_acc=0.6918  |  lr=9.00e-03
Seed: 1  |  epoch 150  |  train_loss=1.2012  |  train_acc=0.6833  |  val_loss=1.1343  |  val_acc=0.6928  |  lr=9.00e-03
Early stopping at epoch 181 (no val_loss improvement for 30 epochs)
Completed runs with seed: 1  | best_epoch=151  |  val_loss=1.1305  |  test_acc=0.6844  |  test_f1=0.5033  |  0.8 min
Summary over 2 seed(s): test_acc mean=0.6831  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 2  |  epoch 050  |  train_loss=1.4090  |  train_acc=0.6491  |  val_loss=1.2521  |  val_acc=0.6783  |  lr=9.00e-03
Seed: 2  |  epoch 100  |  train_loss=1.2666  |  train_acc=0.6759  |  val_loss=1.2040  |  val_acc=0.6916  |  lr=9.00e-03
Early stopping at epoch 118 (no val_loss improvement for 30 epochs)
Completed runs with seed: 2  | best_epoch=88  |  val_loss=1.1723  |  test_acc=0.6750  |  test_f1=0.4866  |  0.5 min
Summary over 3 seed(s): test_acc mean=0.6804  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 3  |  epoch 050  |  train_loss=1.3951  |  train_acc=0.6563  |  val_loss=1.2485  |  val_acc=0.6787  |  lr=9.00e-03
Seed: 3  |  epoch 100  |  train_loss=1.2583  |  train_acc=0.6763  |  val_loss=1.1883  |  val_acc=0.6787  |  lr=9.00e-03
Seed: 3  |  epoch 150  |  train_loss=1.1955  |  train_acc=0.6833  |  val_loss=1.1345  |  val_acc=0.7027  |  lr=9.00e-03
Seed: 3  |  epoch 200  |  train_loss=1.1565  |  train_acc=0.6872  |  val_loss=1.1293  |  val_acc=0.6894  |  lr=9.00e-03
Seed: 3  |  epoch 250  |  train_loss=1.1247  |  train_acc=0.6946  |  val_loss=1.1295  |  val_acc=0.6940  |  lr=9.00e-03
Early stopping at epoch 259 (no val_loss improvement for 30 epochs)
Completed runs with seed: 3  | best_epoch=229  |  val_loss=1.1113  |  test_acc=0.6884  |  test_f1=0.5106  |  1.1 min
Summary over 4 seed(s): test_acc mean=0.6824  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 4  |  epoch 050  |  train_loss=1.4055  |  train_acc=0.6544  |  val_loss=1.2638  |  val_acc=0.6839  |  lr=9.00e-03
Seed: 4  |  epoch 100  |  train_loss=1.2665  |  train_acc=0.6729  |  val_loss=1.1667  |  val_acc=0.6923  |  lr=9.00e-03
Early stopping at epoch 132 (no val_loss improvement for 30 epochs)
Completed runs with seed: 4  | best_epoch=102  |  val_loss=1.1614  |  test_acc=0.6925  |  test_f1=0.4999  |  0.6 min
Summary over 5 seed(s): test_acc mean=0.6844  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 20  |  epoch 050  |  train_loss=1.4104  |  train_acc=0.6498  |  val_loss=1.2701  |  val_acc=0.6811  |  lr=9.00e-03
Seed: 20  |  epoch 100  |  train_loss=1.2776  |  train_acc=0.6696  |  val_loss=1.1787  |  val_acc=0.6962  |  lr=9.00e-03
Seed: 20  |  epoch 150  |  train_loss=1.1980  |  train_acc=0.6844  |  val_loss=1.1659  |  val_acc=0.6912  |  lr=9.00e-03
Seed: 20  |  epoch 200  |  train_loss=1.1493  |  train_acc=0.6906  |  val_loss=1.1380  |  val_acc=0.6972  |  lr=9.00e-03
Early stopping at epoch 223 (no val_loss improvement for 30 epochs)
Completed runs with seed: 20  | best_epoch=193  |  val_loss=1.1223  |  test_acc=0.6846  |  test_f1=0.5006  |  0.9 min
Summary over 6 seed(s): test_acc mean=0.6845  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 42  |  epoch 050  |  train_loss=1.3992  |  train_acc=0.6537  |  val_loss=1.2458  |  val_acc=0.6822  |  lr=9.00e-03
Seed: 42  |  epoch 100  |  train_loss=1.2645  |  train_acc=0.6771  |  val_loss=1.1803  |  val_acc=0.6882  |  lr=9.00e-03
Seed: 42  |  epoch 150  |  train_loss=1.1913  |  train_acc=0.6858  |  val_loss=1.1515  |  val_acc=0.6972  |  lr=9.00e-03
Seed: 42  |  epoch 200  |  train_loss=1.1589  |  train_acc=0.6872  |  val_loss=1.1495  |  val_acc=0.6904  |  lr=9.00e-03
Early stopping at epoch 209 (no val_loss improvement for 30 epochs)
Completed runs with seed: 42  | best_epoch=179  |  val_loss=1.1264  |  test_acc=0.6701  |  test_f1=0.5062  |  0.9 min
Summary over 7 seed(s): test_acc mean=0.6824  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 123  |  epoch 050  |  train_loss=1.4096  |  train_acc=0.6535  |  val_loss=1.2729  |  val_acc=0.6836  |  lr=9.00e-03
Seed: 123  |  epoch 100  |  train_loss=1.2666  |  train_acc=0.6734  |  val_loss=1.1786  |  val_acc=0.6937  |  lr=9.00e-03
Seed: 123  |  epoch 150  |  train_loss=1.1984  |  train_acc=0.6842  |  val_loss=1.1501  |  val_acc=0.7040  |  lr=9.00e-03
Seed: 123  |  epoch 200  |  train_loss=1.1523  |  train_acc=0.6870  |  val_loss=1.1553  |  val_acc=0.6782  |  lr=9.00e-03
Seed: 123  |  epoch 250  |  train_loss=1.1378  |  train_acc=0.6884  |  val_loss=1.1361  |  val_acc=0.7042  |  lr=9.00e-03
Early stopping at epoch 263 (no val_loss improvement for 30 epochs)
Completed runs with seed: 123  | best_epoch=233  |  val_loss=1.1189  |  test_acc=0.6805  |  test_f1=0.5084  |  1.1 min
Summary over 8 seed(s): test_acc mean=0.6822  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 1234  |  epoch 050  |  train_loss=1.4137  |  train_acc=0.6512  |  val_loss=1.2494  |  val_acc=0.6814  |  lr=9.00e-03
Seed: 1234  |  epoch 100  |  train_loss=1.2718  |  train_acc=0.6726  |  val_loss=1.1728  |  val_acc=0.6958  |  lr=9.00e-03
Early stopping at epoch 144 (no val_loss improvement for 30 epochs)
Completed runs with seed: 1234  | best_epoch=114  |  val_loss=1.1558  |  test_acc=0.6821  |  test_f1=0.4944  |  0.6 min
Summary over 9 seed(s): test_acc mean=0.6822  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Seed: 12345  |  epoch 050  |  train_loss=1.4080  |  train_acc=0.6537  |  val_loss=1.2516  |  val_acc=0.6867  |  lr=9.00e-03
Seed: 12345  |  epoch 100  |  train_loss=1.2702  |  train_acc=0.6731  |  val_loss=1.1763  |  val_acc=0.6770  |  lr=9.00e-03
Seed: 12345  |  epoch 150  |  train_loss=1.1975  |  train_acc=0.6803  |  val_loss=1.1349  |  val_acc=0.6940  |  lr=9.00e-03
Early stopping at epoch 186 (no val_loss improvement for 30 epochs)
Completed runs with seed: 12345  | best_epoch=156  |  val_loss=1.1248  |  test_acc=0.7006  |  test_f1=0.5092  |  0.8 min
Summary over 10 seed(s): test_acc mean=0.6840  -> /content/pyg-graph-networks/outputs/metrics/ogbn-arxiv/sagebn_weighted_ce_p0.5_h128_summary.csv
====================================================================================================
Run sagebn_weighted_ce_p0.5_h128 finished: 10 seeds, 8.0 min this session, 8.0 min of training in total
backed up to /content/drive/MyDrive/GraphNetworks

In [19]:
print(summary_wce_p05)

                            mean       std    ci_low   ci_high
Test loss               1.198832  0.018041  1.185926  1.211739
Test acc                0.683995  0.008578  0.677858  0.690131
Test precision          0.496776  0.007664  0.491293  0.502258
Test recall             0.536437  0.013443  0.526820  0.546054
Test f1                 0.501557  0.007559  0.496150  0.506965
Test balanced_accuracy  0.536437  0.013443  0.526820  0.546054
Test brier              0.219899  0.004122  0.216951  0.222848
Test roc_auc            0.968377  0.000986  0.967672  0.969083
Test avg_precision      0.524632  0.007646  0.519162  0.530101
Test ece                0.021129  0.007212  0.015970  0.026288